platform :ios, '15.0'
use_frameworks! :linkage => :static
inhibit_all_warnings!

target 'SwiftUIInteroperability' do

  pod 'SwiftLint', '~> 0.46.5'
  pod 'SwiftFormat/CLI', '~> 0.49'
  pod 'MBProgressHUD'
  pod 'SwiftGen', '~> 6.0'
  
  target 'SwiftUIInteroperabilityTests' do
    inherit! :search_paths
	 
	 pod 'Mimus', :git => 'https://github.com/mimus-swift/Mimus', :commit => 'fca9cd6ac22e08ac397c4ab4415fe849bd377cc8'
	 pod 'SnapshotTesting', "~> 1.9.0"
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
